name: task6_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - spacy
  - pytorch
  - torchvision
  - torchaudio
  - sentence-transformers
  - pip
  - pip:
      - sentence-transformers
